services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db  
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=24h
      - COOKIE_MAX_AGE=86400000
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
    volumes:
      - sqlite_data:/app/data
    command: npx prisma studio
volumes:
  sqlite_data:
  redis_data:
